/*
 * File:   ui.h
 * Author: msuzer
 *
 * Created on 09.04.2014, 22:06
 */

#ifndef USER_INTERFACE_H
#define	USER_INTERFACE_H

typedef enum {
    PRINT_SENSORS = 'A',
    PRINT_QEI_COUNTERS,
    RESET_QEI_COUNTERS,
    RESET_STEPPER_DRIVERS,
    STEPPER_PRINT_MARK_POSITION,
    STEPPER_SET_MARK_POSITION,
    STEPPER_SET_HOME_POSITION,
    STEPPER_GOTO_MARK_POSITION,
    STEPPER_GOTO_HOME_POSITION,
    STEPPER_GOTO_POSITION,
    STEPPER_MOVE_STEPS,
    STEPPER_IS_RUNNING,
    STEPPER_PRINT_END_POSITIONS,
    STEPPER_SET_END_POSITIONS,
    STEPPER_PRINT_TASK_RESULT,
    STEPPER_SELECT_STEP_MODE,
    BOARD_LOOPBACK,
    PRINT_FW_VER
} UserInstructions;

void restore_user_data(void);
void CheckUpUserInstruction(void);

#endif	/* USER_INTERFACE_H */
